name: Super-Linter

on: [push]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: github/super-linter@v3.17.0
      
      - name: Lint Code Base
        uses: github/super-linter@v4